version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mariadb
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: fma_prestaties
            MYSQL_USER: ulusoft
            MYSQL_PASSWORD: ulusoft123456789
            MYSQL_ROOT_PASSWORD: ulusoft123456789
        volumes:
            - ./migrate:/docker-entrypoint-initdb.d
            - fma_prestaties:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: fma_prestaties
            MYSQL_PASSWORD: ulusoft123456789
            MYSQL_ROOT_PASSWORD: ulusoft123456789
volumes:
    fma_prestaties: